-- AlterTable
ALTER TABLE `LiveSessionContentAssigned` ADD COLUMN `zoom` JSON NULL,
    MODIFY `status` ENUM('PENDING', 'USER_REQUESTED', 'SCHEDULED', 'RESCHEDULED', 'COMPLETED') NOT NULL DEFAULT 'PENDING';
