-- AlterTable
ALTER TABLE `LiveSessionContentAssigned` ADD COLUMN `assignedRole` ENUM('ASSIGNED', 'PURCHASED') NOT NULL DEFAULT 'ASSIGNED',
    ADD COLUMN `scheduledOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);